sequenceDiagram
  participant N as Node
  participant R as Relay

  note left of N: queries = Map { 1: Query { } }

  N->>R: announce { id: 1, publicKey: <Buffer ...>, remotePublicKey: <Buffer ... > }

  loop
    R-->>N: result { id: 1, data: <Buffer ...> }
  end

  R-->>N: finished { id: 1 }
