sequenceDiagram
  participant N as Node
  participant R as Relay

  note left of N: connecting = Map { 1: { $tream { alias: 1 } } }

  N->>R: connect { alias: 1, publicKey: <Buffer ...>, remotePublicKey: <Buffer ... > }

  note right of R: handshakes = Map { 2: { Handshake { } } }

  R->>N: noiseSend { isInitiator: true, id: 2, remote$treamAlias: 1, payload: <Buffer ... > }

  note left of N: handshakes = Map { 2: { Handshake { } } }

  N-->>R: noiseReply { isInitiator: true, complete: false, id: 2, payload: <Buffer ...> }

  R->>N: noiseReceive { isInitiator: true, id: 2, payload: <Buffer ...> }

  N-->>R: noiseReply { isInitiator: true, complete: true, id: 2, payload: <Buffer ...>, remoteId: <Buffer ...>, holepunchSecret: <Buffer ...>  }

  alt
    R-->>N: destroy { remoteAlias: 1, error: '<message>' }
  else
    note right of R: connections = Map { 1: { $tream { alias: 3 } } }

    R-->>N: open { alias: 3, remoteAlias: 1, handshakeId: 2 }

    note left of N: connections = Map { 3: { $tream { alias: 1 } } }
  end
